### ISSUE TITLE
Styling: Larger textarea 

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#102]
The textarea for the report message should be at least 4 lines tall per default.

<img width="1086" alt="bildschirmfoto 2017-11-28 um 11 59 52" src="https://user-images.githubusercontent.com/15341015/33316301-c828c904-d433-11e7-906c-24cd4cdc9350.png">

**Comment by xi** [comment]
Was fixed in https://github.com/liqd/a4-meinberlin/pull/1064
