### ISSUE TITLE
#2332: Registration form for twitter login needs styling

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#1026]
When I login with twitter, I have to complete a registration form (is that because Twitter does not give us an email address?). The form should be styled in the same way as the normal registration form. Currently the buttons are off, the link to the terms of service is missing, etc.: 
See here:

<img width="1208" alt="Bildschirmfoto 2019-10-03 um 12 39 18" src="https://user-images.githubusercontent.com/15341015/66120480-3d445e00-e5db-11e9-90a7-7cdbab4ef99a.png">

**Comment by fuzzylogic2000** [comment]
I don't get that page. Just a twitter one. And it's pretty strange, that it's there because the social media logins are to not set another password, IMO. Hmm.

**Comment by MagdaN** [comment]
You only get that page if you already registered with the same email address to our platform. This can happen with all social logins

**Comment by rittermo** [comment]
Ah thanks for the clarification, @MagdaN  But should a registration form the come up, if that user is already registered? I think it would be the most logical, if an already registered users sees a notice like:

„Your email address xxx@xxx.com already belongs to a user account on adhocracy+. Please use our login page to login into your account. You can also reset password if you don’t remember it anymore.“
