### ISSUE TITLE
#2332: No option to accept terms of service, newsletters

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#1028]
When I login with social media, I do not have to accept the terms of service or can check the box to receive email newsletters. 

I think for terms of service we are somehow legally required to make users accept them before using our platform. For the newsletter it would be important but more of a nice-to-have.

**Comment by fuzzylogic2000** [comment]
I have never seen that on any other page and don't know how to that or where to place it?

**Comment by MagdaN** [comment]
We could redirect to the account settings after the first login, but I don't know how complicated it is to implement that

**Comment by rittermo** [comment]
Okay, I looked it up. You can add URLs to the terms of service and the privacy policy via the Facebook app settings. So that problem is solved. The accept „newsletter“ is still a challenge. @MagdaN could you look into the idea of having a re-direct? Or could there be another page, like a reduced register form, with just these checkboxes?

**Comment by MagdaN** [comment]
We can change very easy in a way that during the first login(=register) the signup form is shown and all data has to be added (also password) also the check for newsletter and accepting the terms of use. But the social connection is added as well, so the next time you can just login via social login, no password.
