### ISSUE TITLE
#2552: change logo and button color

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#1029]
Can you please change the bet.in logo in the mailings to the a+ logo. 
Also the button fill color should be the primary brand color hex: 2A3CD4

![a+_logo](https://user-images.githubusercontent.com/15341015/66121357-446c6b80-e5dd-11e9-8b09-792ba03215c3.png)

**Comment by fuzzylogic2000** [comment]
I wasn't sure about the colour, though. I used the platform primary which is: #2d40cc. It's not far away, though.
