### ISSUE TITLE
border-bottom is missing in first field (create new project)

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#104]
![bildschirmfoto 2017-11-28 um 12 00 39](https://user-images.githubusercontent.com/2905743/33316310-d47ecef6-d433-11e7-9d97-d77487de8dd3.png)

**Comment by xi** [comment]
Cannot reproduce. This is probably a rendering issue in specific OS/browser combinations. It might still be a good idea to investigate.

**Comment by fuzzylogic2000** [comment]
@MagdaN Is this still an issue?
