### ISSUE TITLE
Report: Confirmation message not translated

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#105]
The confirmation message for reports should be translated into German.

<img width="1303" alt="bildschirmfoto 2017-11-28 um 12 01 14" src="https://user-images.githubusercontent.com/15341015/33316345-f14ac206-d433-11e7-9c31-9aad1e063e13.png">

**Comment by kleingeist** [comment]
actually a core issue, as the string is not marked as translateable there.

**Comment by fuzzylogic2000** [comment]
fixed!
