### ISSUE TITLE
#2191 button hover makes it unreadable

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#1057]
When I hover over the button on the blue background the hover state makes it unreadable.
![Bildschirmfoto 2019-10-15 um 11 26 29](https://user-images.githubusercontent.com/15341015/66819769-d2cae080-ef3f-11e9-8097-27a14a02be87.png) Could we leave the button white.

**Comment by phillimorland** [comment]
@rittermo just so I know, we don't want any hover behavior other then the pointer changing, like the other side?
