### ISSUE TITLE
Setup support emails

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#108]
When reporting a comment, no email arrives for the moderator or the admin of the platform. Where do the emails go to?

**Comment by kleingeist** [comment]
the contact mail is currently support-berlin@liqd.de on product-dev. but there has been a problem on sending async mails. see #133
the contact email for beteiligen has not been decided yet

**Comment by kleingeist** [comment]
@rittermo which email should we set as the contact email for the product?
we have to setup that email together with @treba123 and decide to whom they should be forwarded.
i'd propose `support-beteiligung@liqd.net`

**Comment by rittermo** [comment]
Alright, @kleingeist ! You can forward it to me then. I also would like a info@beteiligung.in address for general contact purposes. Can you set that up as well and forward it to me and Rouven?

**Comment by kleingeist** [comment]
i don't have access to the mailservers. we have to get in touch with @treba123 for that.

**Comment by treba123** [comment]
I'll setup info@beteiligung.in

**Comment by treba123** [comment]
Alright, info@beteiligung.in and support-beteiligung@liqd.net are both set up. @rittermo , you should have test mails for both.

**Comment by treba123** [comment]
Oh wait, support-beteiligung@liqd.net is not yet set as the contact mail, right? So reopening it :)

**Comment by kleingeist** [comment]
support mail is now set correctly :)
