### ISSUE TITLE
Translations incomplete

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#110]
- partner page

**Comment by rukala** [comment]
<img width="410" alt="bildschirmfoto 2017-11-28 um 12 05 56" src="https://user-images.githubusercontent.com/11075214/33316541-90e55c40-d434-11e7-86b1-76fcd6e663d1.png">

**Comment by rukala** [comment]
In the dashboard:
<img width="328" alt="bildschirmfoto 2017-11-28 um 12 20 22" src="https://user-images.githubusercontent.com/11075214/33317130-955cce8c-d436-11e7-9ef3-d3e52700e8b9.png">

**Comment by rukala** [comment]
<img width="966" alt="bildschirmfoto 2017-11-28 um 12 25 00" src="https://user-images.githubusercontent.com/11075214/33317368-36e79372-d437-11e7-864b-c613152be4c9.png">

**Comment by rukala** [comment]
<img width="949" alt="bildschirmfoto 2017-11-28 um 12 28 19" src="https://user-images.githubusercontent.com/11075214/33317505-a7d761b6-d437-11e7-847e-8376beb62eaa.png">

**Comment by rittermo** [comment]
https://github.com/liqd/a4-product/issues/130

**Comment by rittermo** [comment]
https://github.com/liqd/a4-product/issues/127
