### ISSUE TITLE
Edit comment: Change button label and styling

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#112]
To make editing comments more clear, we should change the label of the send button to „Änderungen speichern“. Also, there needs to be a bit of space between the buttons for send and cancel.

<img width="914" alt="bildschirmfoto 2017-11-28 um 12 07 43" src="https://user-images.githubusercontent.com/15341015/33316691-1ae957f2-d435-11e7-9f1d-5f1886ad16f5.png">

**Comment by kleingeist** [comment]
the buttons title is a core issue, as comments are implemented there. 
but i'll keep that issue open because of the styling issue
