### ISSUE TITLE
Paragraph detail: provide more context

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#115]
When I want to comment on a paragraph, the detail page does not provide any context of the project. We should at least add the title of the project and if possible the title of the chapter of the paragraph above the „zurück zum Kapitel“ link. This is especially helpful, if I leave a tab and come back later.
<img width="953" alt="bildschirmfoto 2017-11-28 um 12 12 15" src="https://user-images.githubusercontent.com/15341015/33316840-a239893e-d435-11e7-822a-68d1481b2160.png">

**Comment by xi** [comment]
See also https://github.com/liqd/a4-meinberlin/issues/247

**Comment by fuzzylogic2000** [comment]
@rittermo As this is the case on more pages (ideas as well), we should make a story out of it.
