### ISSUE TITLE
Wording: maybe 'No moderators yet' instead of None

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#116]
![bildschirmfoto 2017-11-28 um 12 14 21](https://user-images.githubusercontent.com/2905743/33316915-e5b62690-d435-11e7-880b-f10646d05fca.png)

**Comment by xi** [comment]
At the moment we are using the same template for inviting moderators and members. So this is not a trivial change.

**Comment by phillimorland** [comment]
'None' is correct and expected in english, is it incorrect in German? 
If not can this be closed @MagdaN ?

**Comment by fuzzylogic2000** [comment]
As we add the creator as moderator now, this does occur very seldomly.
