### ISSUE TITLE
Activities: Remove project notifications from list

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#118]
In the activity area, I expect to see activites by users and not general notification about projects (like when a phase changes). These should go in notifications for users not in activity of the platform.

<img width="428" alt="bildschirmfoto 2017-11-28 um 12 16 34" src="https://user-images.githubusercontent.com/15341015/33316964-0fbdfb66-d436-11e7-8439-ac0551583c5f.png">

**Comment by fuzzylogic2000** [comment]
@rittermo So, we shouldn't show on the organisation landing page, when a project is ending or starting? We only show, when someone added something? Is this still an issue and should we change it?
