### ISSUE TITLE
Comment box has red border

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#121]
![bildschirmfoto 2017-11-28 um 12 21 42](https://user-images.githubusercontent.com/2905743/33317202-ccdeb65e-d436-11e7-890b-de376fb908df.png)

**Comment by kleingeist** [comment]
this is due to the missing error handling for comments in core (see https://github.com/liqd/adhocracy4/pull/217 )

**Comment by xi** [comment]
> this is due to the missing error handling for comments in core

Not actually true. We use `:invalid` to add a red border to input elements. This works really well to give immediate feedback, except for one single case:

If a field is required and empty, it is invalid even before the user has interacted with it. There are some ideas in W3C to fix that case (e.g.  `:user-invalid`), but those are not available yet.

For meinberlin/beteiligung.in there are some options:

1. remove the `invalid` styling completely
2. use `:-moz-ui-invalid` to get the desired result, but only in firefox
3. leave it as is

If we plan to go with option (2), we have to check if it also works as expected with javascript based fields that are reused after submit.

**Comment by phillimorland** [comment]
issue seems resolved on chrome, firefox, safari
