### ISSUE TITLE
homepage field in user profile is not an URL

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#126]
![bildschirmfoto 2017-11-28 um 12 27 56](https://user-images.githubusercontent.com/2905743/33317497-a3e67d94-d437-11e7-9df5-3472fa8b2ee2.png)

I can just add a string, but in profile a (invalid) link is made out of it

**Comment by xi** [comment]
Currently this is a `CharField`. So we have two options: Either change it to a `URLField` or not display a link.
