### ISSUE TITLE
Follow project: dropdown outside of browser viewport

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#129]
The dropdown selection for the follow buttons opens partly outside the browser viewport. 

<img width="464" alt="bildschirmfoto 2017-11-28 um 12 29 22" src="https://user-images.githubusercontent.com/15341015/33317601-e9524d68-d437-11e7-9aa0-9124ab6f489e.png">

**Comment by xi** [comment]
Related to https://github.com/liqd/a4-meinberlin/issues/1094

**Comment by rittermo** [comment]
Is there anything we can do about this issue now that we do not use the meinberlin css anymore, @phillimorland ?
