### ISSUE TITLE
Link on buttom of user profile not valid

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#131]
![bildschirmfoto 2017-11-28 um 12 31 23](https://user-images.githubusercontent.com/2905743/33317691-2cab35d4-d438-11e7-8541-581ef7fc0446.png)

**Comment by xi** [comment]
What do you mean by "not valid"?

**Comment by MagdaN** [comment]
Sorry, wrong wording. What I meant is, that there is no page where the user could check out other platforms as there are no other platforms. Therefore I would suggest to remove 'Active in these platforms' block or at least the link to other platforms from the user profile.
