### ISSUE TITLE
Cannot read the text above the image

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#159]
![bildschirmfoto 2017-12-05 um 14 20 07](https://user-images.githubusercontent.com/2905743/33609205-798ad0dc-d9c7-11e7-9f45-2d02e23d6113.png)

**Comment by xi** [comment]
Should be fixed with https://github.com/liqd/a4-meinberlin/pull/1088/commits/505506ac7bcd82923dc7f1756663a63a959a3ae4

**Comment by fuzzylogic2000** [comment]
I think this is fixed! Please reopen if not.
