### ISSUE TITLE
Which pages are needed?

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#168]
At the moment we can link to the following pages through the wagtail settings:

- Impressum

- Datenschutz

- Nutzungsbedingungen

In #85 there is also a link to the contact page in the email. If this is needed, we need to add this to the wagtail settings. Also in #90 there is a link to help pages. Do we need help pages - if yes we could also add them to the settings or make the links in footer editable via wagtail.

**Comment by MagdaN** [comment]
@rittermo can this be closed or do we need more pages?

**Comment by rittermo** [comment]
No more pages are needed for the moment! Thanks!
