### ISSUE TITLE
fontsizes in css are unclear

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-product#175]
in variables.scss there are some fontsizes defined. It would be great if there could be a comment what they are in Pixel.

**Comment by kleingeist** [comment]
we can't tell them in pixel, as they are relative to the browsers font setting. we don't overwrite the base font size, and just define the relations between fonts in `rem`

**Comment by MagdaN** [comment]
OK, how can I calculate rem value from designs which is in pixels ?

**Comment by kleingeist** [comment]
as far as i understood the css concept we can't. we have these variants of font sizes defined and have to try to match them to the intention the designer had in its layouts. if i remember correctly david only used the same number of font sizes for his layouts.
