### ISSUE TITLE
Decide on FAQ vs about us vs description

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-product#181]
Currently the partner nav has a "FAQ" item which links to an "about-us" page which is mainly filled from the "description" field in the database and forms.

This is confusing. We should decide on a single naming scheme and adapt everything accordingly (model, form, link, header)

**Comment by fuzzylogic2000** [comment]
@rittermo said, that we'll leave it at FAQ for now and will most likely have to change it later. 
I will still leave it open, to remind us to adapt the whole naming scheme.

**Comment by kleingeist** [comment]
but should we update the form/model fields and the pages url and the heading, too?

**Comment by kleingeist** [comment]
closed as this will be the information tab which should allow for heading elements
