### ISSUE TITLE
Make break after "beteiligen.in/" dynamic

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-product#184]
Currently the html on the homepage is duplicated (see #180)
it would be nice if we could prevent that while still keeping the wrapping. 
did some tests with pre-wrap etc but didn't achieve the expected result. we should look into it later

**Comment by fuzzylogic2000** [comment]
@phillimorland Do you have an idea?

**Comment by phillimorland** [comment]
no longer needed as no "beteiligen.in/" in header anymore
