### ISSUE TITLE
Userindicator color seems wrong on small screens

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-product#185]
the color gradient requires a certain minimum width of the page to allow for the userindicator button background to blend in with the top line
if the browsers width is too small, the button does look out of place as can be seen in the screenshot below

@rittermo can you give any feedback if this is okay and on the importance of the issue?

![product_userindicator_mobile](https://user-images.githubusercontent.com/167407/33726907-b6c2df70-db76-11e7-94e4-8ec2c35ca270.png)

**Comment by rittermo** [comment]
The rounded corners are more of a problem. The corners should be square.
The gradient should be easy to fix with css gradient color stops for the breakpoint. Although I think you are showing a way smaller width than any modern smartphone has (smaller than 320px). The color gradient must only work for width =>320px.

**Comment by kleingeist** [comment]
the userindicator is not finished yet, so i think the borders will be removed by tomorrow ;)
but it seems to me that it makes sense to add this to the milestone. the gradient/background problem exists with a width of 320px (see image below)

@fuzzylogic2000  i assigned you to this issue as you were already working on the indicator. hope thats okay

![product_userindicator_mobile-320](https://user-images.githubusercontent.com/167407/33728221-0b855314-db7a-11e7-927e-139464e52be8.png)

**Comment by rittermo** [comment]
@kleingeist Thank you for the response and for adding it to the milestone.
