### ISSUE TITLE
homepage title lays over the text when no image

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#189]
![screenshot from 2017-12-08 13-49-46](https://user-images.githubusercontent.com/8178179/33766708-fd2e2b42-dc1e-11e7-9c2a-1f1f25fd3843.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland This is not super important as we do the homepage ourselves and will add an image, but if you know an easy fix...

**Comment by phillimorland** [comment]
Having trouble replicating and we will redesign homepage anyway
