### ISSUE TITLE
Header: Styling issues

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#190]
- [ ] Menü: Auffahren wie auf mobil auch auf großen Screens
- [x] Menü: User dropdown bereits im Menü aufgeklappt
- [x] Logo: Auf Falkensee verlinken
- [x] Logo Bild Partner: Weniger Weißraum
- [x] Header+Menü: Secondary color statt Primary in 30 % für Plattform (nur Verlauf und Menü) verwenden
- [x] Menü Partner: Aktueller Menüpunkt ist derzeit nicht unterstrichen

**Comment by phillimorland** [comment]
fixed in recent header updates
