### ISSUE TITLE
Styling: Participate pages

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#191]
- [x] Beteiligung: Hintergrundfarbe für Text primary in 15 % nicht primary 30 %
- [x] Beteiligung: Tablist höher und mit etwas mehr Margin von oben
- [ ] Beteiligung: Folgen-Button als großer Button in secondary color (siehe Entwurf) [NTH]
- [x] Beteiligung: Kapitel-Spring-Buttons oben wegnehmen
- [x] Absatz Detail: Hellblauer Streifen (15 % primary) hinter Link zurück zum Kapitel

**Comment by fuzzylogic2000** [comment]
I will close this as only NTH is missing (and might not be needed in the long run after all)
