### ISSUE TITLE
Landing Page: Image in Rich Text field look blurry

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#193]
I uploaded a logo for Falkensee to link to their plattform from the beteiligung.in landing page. It looks a little blurry no matter what resolution I upload it in. 

![bildschirmfoto 2017-12-11 um 09 46 20](https://user-images.githubusercontent.com/15341015/33822538-2fbdfc28-de58-11e7-8491-32c59e4fc18e.png)

https://www.beteiligung.in

**Comment by kleingeist** [comment]
the images are not resized on the server side. they are resized via the css `width` and `height` properties. thus the blurryness is due to the browsers rendering engine which we don't control.
