### ISSUE TITLE
mobile: Footer looks a bit off

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#195]
![screenshot_20171211-095825](https://user-images.githubusercontent.com/8178179/33823077-1493b03a-de5a-11e7-83a2-10875ee9e8c7.png)

**Comment by fuzzylogic2000** [comment]
I think this very issue was fixed by @MagdaN. We still have to include the rest of the text and links from the design though.

**Comment by phillimorland** [comment]
fixed
![beteiligung in](https://user-images.githubusercontent.com/5871230/42165722-3487916e-7e09-11e8-8cce-450bf4d618ba.png)
