### ISSUE TITLE
Homepage header overlapps messages

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-product#196]
extracted from #186 

> Colors are also wired on my machine, but also the messages are ordered differently and are overlaped by content:
>
> ![selection_011](https://user-images.githubusercontent.com/141032/33765750-9a9881b6-dc1a-11e7-9d9b-029eefa16cb2.png)

**Comment by kleingeist** [comment]
i think this is only valid if there is no homepage image set?
may be probably closed.

**Comment by MagdaN** [comment]
I agree
