### ISSUE TITLE
Login indicator: Pic does not fill circle completely

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#221]
In the login indicator, there seems to be a slight gap, so that the circle for the avatar pic is not completely filled out on the right-hand edge. Tested in Safari

![bildschirmfoto 2017-12-14 um 15 42 03](https://user-images.githubusercontent.com/15341015/33997719-94c4cb76-e0e5-11e7-96c5-cd832a5bd23d.png)

**Comment by fuzzylogic2000** [comment]
Oh. I don't know what to do about that. The avatar picture is cut to a much bigger size than it is displayed in by the thumbnailer and then made smaller and round in the css. It also looks like there is a blue blurr on the right side in the circle, when I make the picture really big.
@rittermo Does that happen with other pictures as well?
@MagdaN Do you have any idea what to do about that?
