### ISSUE TITLE
Vote Up Buttons are looking inactive

### ISSUE THREAD

**Issue by kleingeist** [liqd/a4-product#230]
Not sure what colors had been used for them, but they are looking inactive on the current scheme

![beteiligung-vote-buttons](https://user-images.githubusercontent.com/167407/34102877-fb15e4fc-e3ea-11e7-9ee2-c8ee36604e3f.png)

**Comment by fuzzylogic2000** [comment]
I don't think they look inactive, but the up-vote-button is a bit hard to see.
@rittermo What do you think?

**Comment by phillimorland** [comment]
contrast is a bit low for a11y @szukowski do you have an idea of a better colour?

**Comment by szukowski** [comment]
@phillimorland take the darkblue ;)
