### ISSUE TITLE
replacing jquery by googleapis

### ISSUE THREAD

**Issue by mkind** [liqd/a4-product#233]
Currently, we're using `http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js`. I think, we should remove links to google for privacy reasons. So consequently we should deliver jquery ourselves.

**Comment by kleingeist** [comment]
on which page did that happen? we should be serving jquery ourselves  (packaged via webpack)

**Comment by mkind** [comment]
Ah.. this is caused by the debug toolbar. So no real issue.
