### ISSUE TITLE
Partner landing page: small styling issues on small screens

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#284]
After applying the changes of https://github.com/liqd/a4-product/issues/283 these changes should be made to accomodate smaller screens

- [x] reduce padding of .partner__logo-box to 1rem
- [x] h1: reduce font-size to 1.4rem
- [x] h2: reduce font-size to 1rem
- [x] add margin bottom (one line-height) after partner slogan
- [x] add margin after partner intro text (two line-heights at least to signify change in sections)
- [x] add word-break: break-all to tiles to account for long german words in the project title
- [x] add margin (one line-height) before status („Abgeschlossen“) in project tile
- [x] add margin (at least two line-heights) after end of project tiles to separate projects section from activity box

![bildschirmfoto vom 2018-02-06 um 10 38 09](https://user-images.githubusercontent.com/15341015/35852434-29b59fac-0b2b-11e8-8ada-e4af1829a42d.png)

![bildschirmfoto vom 2018-02-06 um 10 39 44](https://user-images.githubusercontent.com/15341015/35852309-d9f050a2-0b2a-11e8-93d3-9524deae91d8.png)

**Comment by fuzzylogic2000** [comment]
word-break: break-all gives surprising results. https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
overflow-wrap: break-word; makes things a bit better. https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by fuzzylogic2000** [comment]
done with #288
