### ISSUE TITLE
Partner landing page: Activity box broken < 1140px width

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#285]
The activity box looks broken for screens smaller than 1140px. Either it should break underneath the project list from that point on, or – ideally – we would optimize the width of the content inside the box by giving the icons for each item its own line, so that the text has more space. Then we could break the box into a new only for smaller screens, maybe from 950px downwards.

![bildschirmfoto vom 2018-02-06 um 13 38 47](https://user-images.githubusercontent.com/15341015/35860116-12ed26c4-0b43-11e8-902a-30ce36ddfafe.png)

**Comment by fuzzylogic2000** [comment]
The overflowing of text will be fixed with this PR: #288 
And the text will have a bit more space because there is less padding around the icons.
We could also try to change the column-layout to 8-4 instead of 9-3:
![screen shot 2018-02-07 at 16 13 58](https://user-images.githubusercontent.com/8178179/35924199-a9cf72ce-0c22-11e8-8805-acc560eeefed.png)
This works better for pages with only one project.

**Comment by fuzzylogic2000** [comment]
We could also think about changing the arrangements/columns/height of the project tile depending on the length of the project and action lists?!
As for the breakpoints, we could use, currently in beteiligung.in, there are two, which are 50em (roughly 800px) and 33em (roughly 520px). These are in the same regions as bootstraps. Bootstrap additionally has breakpoints at 992 ans 1200px. I think we should use breakpoints corresponding to these four.

**Comment by fuzzylogic2000** [comment]
@rittermo Are you happy(ish) with it as it is? Can we close this issue and the manual testing task? Or should I change something?

**Comment by rittermo** [comment]
I think the activity column still gets too narrow.
From 992px width to 800px width I would give the icons their own line and make more space for the text:
.action__main margin-left: 0 
.action__icon: float none

**Comment by phillimorland** [comment]
@rittermo I checked this locally and it looked a little odd, see attached screen shot, I think @fuzzylogic2000 suggestion of increasing the column width for activity and decreasing the project tiles is a better bet and we do now have additional break points between 800 and 1024 so we can leave it at current widths for larger screens
![liqd partner(3)](https://user-images.githubusercontent.com/5871230/58418503-35ead200-8088-11e9-84a4-75263c7efa7d.png)

**Comment by phillimorland** [comment]
with new col widths at 85
![Teststadt](https://user-images.githubusercontent.com/5871230/58418612-882bf300-8088-11e9-86ee-2c30eba073e7.png)
0px
