### ISSUE TITLE
links in mobile menu have different font-weights

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#287]
partner navigation links: 700
login/register: 600

![screen shot 2018-02-07 at 09 42 58](https://user-images.githubusercontent.com/8178179/35906613-7b77813c-0beb-11e8-8813-b222a93e106d.png)

**Comment by phillimorland** [comment]
can't reproduce problem, which device and browser does this happen with?

**Comment by fuzzylogic2000** [comment]
This seems to be magically fixed now!
