### ISSUE TITLE
Avatar image is gone

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#321]
because of the new display: none for images in dropdown-buttons, that is used in meinBerlin.

**Comment by kleingeist** [comment]
ah damn. 

but we could use the class defined in a4 or define new classes instead of using the `.dropdown > img` selector
https://github.com/liqd/adhocracy4/blob/master/adhocracy4/static/select_dropdown.js#L17

**Comment by fuzzylogic2000** [comment]
Yeah, that would solve it in the dashboard, but what do we do in the category filter?

**Comment by kleingeist** [comment]
err there is a class called `dropdown-item__icon` :|
maybe we should unify those classnamed :|
