### ISSUE TITLE
[f2f module] Content info not visible when phase not active

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#354]
When the phase of an f2f module has not started yet, the content/info of the f2f module is not shown. The content should be always shown (see acceptance criterion #6 of the user story). 

See Module „Jury-Sitzung“ here: https://product-dev.liqd.net/teststadt/projects/neues-gemeindezentrum-in-teststadt/

**Comment by fuzzylogic2000** [comment]
We couldn't change this as the phase content is only shown after the phase has started. We do it differntly with the new timeline now and we need to think about offline anyway, now that we have events, speakup and face2face! So, will close!
