### ISSUE TITLE
[f2f module] do not show the module info

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#355]
It would be best, if we would not show the info of a module, as there will never be more than one phase in this module. Especially the message: „Die Beteiligung ist aktuell nicht möglich. Sie startet am…“ for non-active f2f modules is confusing. f2f modules will only allow participation at the event, so the participation on the platform will never be possible.

![bildschirmfoto 2018-05-07 um 12 07 08](https://user-images.githubusercontent.com/15341015/39697018-cee40dd2-51ef-11e8-889c-1a0fd70a1c15.png)

**Comment by MagdaN** [comment]
@rittermo if we remove the phase information the start and enddate won't be visible at all

**Comment by phillimorland** [comment]
was this issue solved with the above merge?

**Comment by rittermo** [comment]
No, but the issue can be closed anyway. The f2f module and which info is shown when for modules will have to be solved in a future user story.
