### ISSUE TITLE
[f2f module] Styling

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#356]
Drei Styling-Fragen, zu denen evtl. @szukowski mehr sagen kann: 

1. Die Überschrift für den Titel des Inhalts finde ich ziemlich groß. Vor allem auf mobilen Geräten könnten lange Wörter dadurch nicht mehr in eine Zeile passen.

2. Könnten wir die Highlighted Info unter dem Titel noch mehr hervorheben? Z.B. durch Fett-Setzen des Texts. So sieht sie doch sehr wie Fließtext aus. 

3. Ich verstehe den grünen Strich zur Abtrennung der Modul-Info vom eigentlichen Inhalt, aber ich finde ihn relativ stark hervorstechend und nicht konsistent mit den Online-Beteiligungs-Modulen Wäre es ansonsten möglich, die Information irgendwie anders von den Modul-Infos zu treffen? Achtung: Am besten wäre es wir würden die Modul-Info einfach gar nicht anzeigen, wie hier #355 beschrieben. Dann wäre der Trennstrich und die größere Schriftgröße der Überschrift auch nicht mehr nötig.

![bildschirmfoto 2018-05-07 um 12 07 08](https://user-images.githubusercontent.com/15341015/39697278-b189055c-51f0-11e8-90a7-10d297db9261.png)

**Comment by fuzzylogic2000** [comment]
Needs thinking and refactoring in a bigger scope
