### ISSUE TITLE
help text for archive project does not fit

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#376]
it says, that we can still find the archived projects via the filters, which we do not (yet) have in bet.in

**Comment by phillimorland** [comment]
screenshot/url?

**Comment by fuzzylogic2000** [comment]
@rittermo What is the concept with the archived projects in a+? Should they be accessible via filters? Maybe this calls for a small story!

**Comment by fuzzylogic2000** [comment]
@rittermo We need a concept for archived projects! They are currently also accessible via the activity feet on the organisation landing page.

**Comment by fuzzylogic2000** [comment]
Alright, this is A4! So, we should
- Either find a text that fits for all projects. @CarolingerSeilchenspringer Is the first part enough? 
- Or add filters to actually find the projects again to the organsiation landing pages. @rittermo What do you think?

**Comment by fuzzylogic2000** [comment]
Well, and also the text is not thaaaaat wrong: it is then not shown on all lists. And in the dashboard, it can be accessed via the filters. Just the user can't access it anymore.

**Comment by CarolingerSeilchenspringer** [comment]
I would suggest: "Archivierte Projekte werden nicht in der Projektübersicht angezeigt. Für Projektinitiator*innen sind sie weiterhin im Dashboard einsehbar. / Archived projects are not shown in the project overview. For project initiators they are still visible in the dashboard." @rittermo was meinst Du? Mich stört einzig das Wort Dashboard, aber ich sehe gerade keine hilfreiche Beschreibung ohne das Wort zu benutzen. :-)

**Comment by rittermo** [comment]
I like your proposal @CarolingerSeilchenspringer . I have to say that I use „Administrationsoberfläche“ / „Admin Interface“ quite a lot when I explain the dashboard to people. I know that clashes with our internal wording. So, if you think that meinBerlin initiators can stomach the English word „Dashboard“ I would go with your proposed text.

**Comment by CarolingerSeilchenspringer** [comment]
@rittermo I think "Administrationsoberfläche" is the most correct term but very sperrig. For the berlin administration they are used to such words but I wanted to have something all our projects could use. I made a brainstorming with the team (think you weren't there) and there were some ideas (Beteiligungshub, Projektlaunch...). We could have a look at those ideas again but if we need a quick decision I would go for Dashboard and maybe change it later. We also use the word in the mB-Handbuch.

**Comment by rittermo** [comment]
@CarolingerSeilchenspringer Thanks for the info! Yes, the word is headache! So let’s go with your original proposal with „Dashboard“. @fuzzylogic2000
