### ISSUE TITLE
the border for the partner-logo is there even if there is no logo

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#392]

**Comment by phillimorland** [comment]
When there is no logo the border is outlining the name of the partner, when border is removed, partner name just looks like another tab. 
Would it be better to remove name altogether?
![imprint beteiligung in liqd partner](https://user-images.githubusercontent.com/5871230/42171756-7321350e-7e1a-11e8-9277-99c26df70f7f.png)

**Comment by fuzzylogic2000** [comment]
@rittermo What do you think?
It currently looks like that, when the partner doesn't add a logo:
![screenshot from 2019-03-01 11-03-05](https://user-images.githubusercontent.com/8178179/53631029-ce9cbd80-3c11-11e9-9f9a-6e98060186b6.png)
@phillimorland proposed to remove the whole thing (and it would look like in her comment). As the bit directly over the tabs is linking to the partner page, I think it's a good idea.
Other options would be a fallback image or having the partner name in the border. Displaying the partner name here might be a problem for long names, though.

**Comment by phillimorland** [comment]
@rittermo @fuzzylogic2000 as the partner name is now the heading anyway I think we should remove this in the cases when there is no logo
