### ISSUE TITLE
Partner information is shown after clicking FAQ

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#393]
When a partner adds information to it's settings, it is shown under the tab FAQ.

**Comment by phillimorland** [comment]
As we have no place to add FAQ's can we just rename the tab 'Information'? or re-label the information input 'FAQ' or just suggest they present the information in an FAQ format? 
What do you think @rittermo ?

**Comment by rittermo** [comment]
@phillimorland Yes, renaming it to „Informationen“ (DE) and „Information“ (EN) is a good solution. In the future, I would like to have some additional RTE-elements like accordeons, which allow for an FAQ section, but I think Information is still a better general name.

**Comment by fuzzylogic2000** [comment]
fixed by #415
