### ISSUE TITLE
can't see full time when creating an event on small screen

### ISSUE THREAD

**Issue by PhilippMu** [liqd/a4-product#428]
![bildschirmfoto 2018-07-13 um 10 57 54](https://user-images.githubusercontent.com/41073836/42682788-d0101a54-868b-11e8-816e-e77dc5f8a60e.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland And maybe this? It should be in offlineevents (and I wonder if not also in the phases if it's there).
