### ISSUE TITLE
invites to private projects do not have the invite token attached to the link

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#471]

**Comment by hmkay** [comment]
It is the Link to the landing page of bet.in...

**Comment by hmkay** [comment]
maybe this is also why the invited people are not shown as participants?
![participants in invited projects](https://user-images.githubusercontent.com/30862422/46745941-53605c80-ccae-11e8-9ef1-2794f0d67fc3.jpeg)
