### ISSUE TITLE
password reset not working

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#49]
When I try to reset my password on dev I don't receive an email with password reset link.

**Comment by xi** [comment]
works for me.

**Comment by kleingeist** [comment]
there had been a problem with the address the mails were sent from. it was set to no-reply@product.liqd.net although the subdomain product.liqd.net does not exist. 
that resulted in mails being bounced by mailbox.org, while the may have reached different mailbox providers. 
the from address has been changed to a valid domain now.
