### ISSUE TITLE
The dropdowns for sorting and filtering are too big / break

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#556]
The dropdowns for filtering and sorting break into multiple lines and look bigger than they were. 
This happens for map views and for lists as well.

Examples
List view:
https://product-stage.liqd.net/musterstadt/projects/vision-2030-ihre-ideen-fur-die-zukunft-von-musters/
Map view: 
https://product-stage.liqd.net/musterstadt/projects/wo-ist-es-zu-laut-in-musterstadt-2/

![bildschirmfoto 2019-01-11 um 16 20 29](https://user-images.githubusercontent.com/15341015/51042581-f29e3400-15bc-11e9-90ba-99f39c53b787.png)

**Comment by rittermo** [comment]
@treba123 Could this be related to the map fix you released on Wednesday evening?

**Comment by fuzzylogic2000** [comment]
Not really. This is related to updating styles and font-sizes in meinBerlin and then updating meinBerlin in the product. We need to uncouple product and meinBerlin.

**Comment by fuzzylogic2000** [comment]
They still seem big (no idea how big they used to be), but don't break anymore. Will close this for now.
