### ISSUE TITLE
Text missing for „show answers“

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#557]
The label text for the button to show answers to comments is missing.

![bildschirmfoto 2019-01-11 um 16 40 59](https://user-images.githubusercontent.com/15341015/51043821-e4054c00-15bf-11e9-9245-0c690df60876.png)

https://product-stage.liqd.net/musterstadt/ideas/2018-00008/

**Comment by fuzzylogic2000** [comment]
fixed
