### ISSUE TITLE
Server Error 500 when adding idea

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-product#579]
I just created a new process on product-stage in order to present the platform to HKW on Friday. However, when I want to add an idea I get an error message (500)
@MagdaN @fuzzylogic2000 would it be possible to fix it until tomorrow?
Otherwise I wouldn't show it to HKW on Friday. 
Cheers, 

Project Name: (Un-)Learning Workshops
Organisation: Test Stadt

![screenshot 2019-02-20 at 15 48 09](https://user-images.githubusercontent.com/15954895/53099992-3d4d8d00-3527-11e9-80a2-d82f39f34085.png)

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld @MagdaN This turned out not to be an (our) issue, right? So, we can close it?
