### ISSUE TITLE
mobile user dropdown - space between different menues

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#599]
![screenshot from 2019-03-01 11-08-51](https://user-images.githubusercontent.com/8178179/53631438-d315a600-3c12-11e9-86c8-b9ac3f922d86.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland Ideas?

**Comment by phillimorland** [comment]
@fuzzylogic2000 i managed to replicate this (kind of) but on page refresh it disappeared and I can't make it come back, I have no clue what cause it either

**Comment by fuzzylogic2000** [comment]
@phillimorland Oh, I think it's an artefact when making the screen smaller in the browser and then opening the dropdown. Sorry! Will close!
