### ISSUE TITLE
mobile user dropdown - all links or buttons should behave the same

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#600]
they currently have different hover-behaviour. The lower menu seems to have buttons, while the upper part is links and doesn't have any hover behaviour

**Comment by fuzzylogic2000** [comment]
@phillimorland Maybe if we add our btn-classes to the links on mobile?

**Comment by phillimorland** [comment]
@fuzzylogic2000 which is lower menu?

**Comment by phillimorland** [comment]
@fuzzylogic2000 I can't replicate this also, which browser? also it is the main menu you're on about isn't it?
Also I just realised touch screens don't have hover behavior so might not matter?

**Comment by fuzzylogic2000** [comment]
@phillimorland You're right!
