### ISSUE TITLE
German translations missing (US #415)

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#603]
When deleting a project the button and the dialogue in the modal is in English instead of German.

**Comment by rittermo** [comment]
Do you need the translations from me, @fuzzylogic2000 ?

**Comment by rittermo** [comment]
The topics are not translated either

![Uploading Screenshot_2019-03-04 Edit topics — Thesenpapier Neues Miteinander neu — Beteiligung in.png…]()

**Comment by MagdaN** [comment]
@rittermo yes I also just realized that those translations are missing! I would just copy the ones mberlin, is that fine with you?

**Comment by rittermo** [comment]
Yes, it is. Although I am not sure about the topics (see #604 )
