### ISSUE TITLE
Internal server error when previewing unpublished project

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#62]
I get an internal server error when attempting to preview an unpublished project:

![bildschirmfoto 2017-11-08 um 10 48 45](https://user-images.githubusercontent.com/11075214/32542301-6c55a6ae-c472-11e7-96ba-5c6616002144.png)

**Comment by kleingeist** [comment]
fixed with 8e149bbc6d268bc85030076481bbba1a0cd0e842
