### ISSUE TITLE
LineAwesome comment icon not working

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-product#646]

**Comment by phillimorland** [comment]
There is no line awesome support for FontAwesome5 so our overwrites are failing where there have been updated class names, most were ok to update but as we have some tricky ways they are added I am not sure how to fix them.
All icons in the date picker are broken
Also radio and check boxes on polls seem to not have a tick?
@rittermo Should we spend time tracking and fixing these issues or should we revert everything to FontAwesome? as there is longer support for line awesome I assume this will happen again.

**Comment by rittermo** [comment]
Thanks for looking into it, @phillimorland ! I already saw that lineawesome did not receive any love during the last year. I think it absolutely makes sense to switch back to FontAwesome for Beteiligung.in, then.

**Comment by phillimorland** [comment]
@rittermo Cool!
