### ISSUE TITLE
Internal server error when editing poll question

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#65]
Internal server error when editing poll question in creating poll in dashboard

**Comment by kleingeist** [comment]
still valid on dev :/ despite the fixes in  8e149bb

**Comment by kleingeist** [comment]
the template tags are not packages, as they are not containing a `__init__.py` 
thus the template fails as the react_polls tag is not available.
this should also be valid for other `templatetags` dirs without a `__init__.py`

**Comment by kleingeist** [comment]
fixed with liqd/a4-meinberlin#989
