### ISSUE TITLE
Move apps folder out of the project folder

### ISSUE THREAD

**Issue by rmader** [liqd/a4-product#693]
Like in a4-spd, lets move the app folder to the root folder. That makes it much easier and cleaner to copy over apps from one project to the other because the (rather useless) project prefix is gone everywhere.

@fuzzylogic2000, @phillimorland, what do you think?

**Comment by fuzzylogic2000** [comment]
That would be so awesome!
But there is a lot of places where the code and the linter settings and other settings need changes then...

**Comment by phillimorland** [comment]
Sounds like a cunning plan! not sure how much work changing everything would be though?

**Comment by rmader** [comment]
Copying the newletter involves so much replacing of meinberlin that I'll have a look into doing this first :/

**Comment by rmader** [comment]
Closed by https://github.com/liqd/a4-product/pull/699
