### ISSUE TITLE
#1986 font-size too large 

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#707]
I tested the new larger font-size for the header and I think it is too large. It prevents us from using longer organisation names and even existing ones („Bayerischer Staatsbeauftragter“) have a line break now. So I propose, we go back to the font-size we used for Beteiligung.in/ before. 

![Bildschirmfoto 2019-05-21 um 12 04 54](https://user-images.githubusercontent.com/15341015/58087674-523aca80-7bc1-11e9-8f8e-c186a9b56a64.png)

**Comment by rittermo** [comment]
I hope you are okay with that, @szukowski ?

**Comment by szukowski** [comment]
@rittermo i do not mind if a name breaks.
Of course, we can optimize the font size for mobile, but they should not be as small as the metanavigation. It is the title of the platform and may have a certain presence.

**Comment by rittermo** [comment]
Ah, yeah, good that you mention that. On the other hand, the partner header link acts just like a link from the main navigation, so I don’t see a big problem with it looking similar, I guess. But if you can find a good size in between, I’m in. I just think short names should not need a line break.

**Comment by phillimorland** [comment]
Font size on mobile is already optimised but as on tablet and mobile metanav is in a dropdown we can reduce the size further without worrying about appearance difference, are you happy with the size on larger screens or would you also like that reduced? @rittermo @szukowski

**Comment by rittermo** [comment]
I think it is too large to fit longer names on larger screens, too. So it would be great to reduce the size there too, @phillimorland.

**Comment by phillimorland** [comment]
Images for comparison for @szukowski to discuss 
first 2 are h3, last is h2 (current size) with highlight ![liqd partner](https://user-images.githubusercontent.com/5871230/58414005-6b88be80-807a-11e9-9f9f-710610e34e07.png)
![liqd partner(1)](https://user-images.githubusercontent.com/5871230/58414009-6e83af00-807a-11e9-90bf-bf9c0e78611c.png)

**Comment by phillimorland** [comment]
![liqd partner(2)](https://user-images.githubusercontent.com/5871230/58414205-041f3e80-807b-11e9-98d8-977c4fa2a4f5.png)

**Comment by szukowski** [comment]
@rittermo you should decide. for me it is ok if it looks different than the navigation.
