### ISSUE TITLE
#1922 Time of phase is shown as written text

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#712]
In the English version, the time for start and end date of phases is written as text not given as a number like in the German version
![Bildschirmfoto 2019-05-23 um 13 38 31](https://user-images.githubusercontent.com/15341015/58249894-594c0f00-7d60-11e9-9cb0-3c39e06ae1da.png)

https://product-dev.liqd.net/musterstadt/projects/wie-sicher-ist-musterstadt-fur-radfahrerinnen/

**Comment by fuzzylogic2000** [comment]
We can't change that (I think). That's the english way of writing it. As soon as you change to another time, it uses numbers!
![Screenshot from 2019-05-23 14-56-01](https://user-images.githubusercontent.com/8178179/58254402-f14ef600-7d6a-11e9-8e16-4f53f4e38a6b.png)

**Comment by rittermo** [comment]
Erm, that’s super strange. :/ Can’t we just use 23:00 instead of am/pm. That’s the American way of writing times anyway, not the one for int/UK/whatever users.

**Comment by fuzzylogic2000** [comment]
I also tried the US-locale (en-us instead of en) and got the same am/pm/mignight-stuff.
We could enforce it to use the German writing, but then the date would be wrong and it's not very clean.

**Comment by fuzzylogic2000** [comment]
Ok, it took me a while to find out, why the us-american localization still gives the time like that. They also use it! 

> [In traditional American usage, dates are written in the month–day–year order (e.g. May 23, 2019) with a comma before and after the year if it is not at the end of a sentence,[2] and time in 12-hour notation (8:57 am). ](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States)

**Comment by fuzzylogic2000** [comment]
@phillimorland So, some confusion about the a.m.-p.m-stuff. You also use that in the UK, right?

**Comment by fuzzylogic2000** [comment]
Ok, @phillimorland siad, that they also use it, so I will close this issue!
