### ISSUE TITLE
#1922 URL change for English or German version

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#713]
Currently, the URL does not change/indicate whether I am on the German or English version of the platform. This makes it impossible to force a user via a link to one of the versions. This, however, is necessary, since most partners will use it in either German or English, not in both languages.

![Bildschirmfoto 2019-05-23 um 13 43 23](https://user-images.githubusercontent.com/15341015/58250050-c2cc1d80-7d60-11e9-80a0-0f038c3102a4.png)

**Comment by fuzzylogic2000** [comment]
Ehm, we asked that in the beginning of the sprint and then did it this way (without the language in the URL, but only on the switch), because this wasn't in the story. 
How important is this?

**Comment by fuzzylogic2000** [comment]
@rittermo  So, did we agree to rethink the translations and do this with the next translation story?

**Comment by rittermo** [comment]
Yes, we agreed to do this with a separate translation story
