### ISSUE TITLE
#1922 Follow button not translated to English

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#714]
The follow button and the menu is not translated to English

![Bildschirmfoto 2019-05-23 um 13 45 03](https://user-images.githubusercontent.com/15341015/58250139-032b9b80-7d61-11e9-88e6-d93bca40d831.png)

**Comment by MagdaN** [comment]
I can only reproduce this on firefox (but only on the dev server and not locally). Maybe this is an caching problem. @rittermo which browser were you using, when the error occured?

**Comment by rmader** [comment]
It also applies for other jsx related stuff like comments. So there's a general bug here

**Comment by rmader** [comment]
IE11 is also affected. Seems like the fact that it works in webkit based browsers is more a coincidence.

**Comment by rmader** [comment]
Hm what about this one? :)

![archived nein](https://user-images.githubusercontent.com/6313774/58480785-56d02780-815b-11e9-968a-c04cd5fef8fd.png)

**Comment by rmader** [comment]
Should be fixed...http2_push somehow confused things. Will have another look at some point
