### ISSUE TITLE
#1922: Wording Changes

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#732]
### Dashboard

I noticed some wordings which were off in the English version, so I took the opportunity to make some changes to the wordings in the German version as well. I hope that’s okay

https://product-dev.liqd.net/dashboard/organisations/falkensee/projects/?search=test&is_archived=false

Change button label „Organisation settings“ to „Edit your organisation“

### New Project

![New Project — Beteiligung in](https://user-images.githubusercontent.com/15341015/58461096-2d99a200-812f-11e9-96bd-c64be353c12b.png)

0 

EN: Create a new project
DE: Neues Projekt anlegen

1 
EN: Brainstorming
DE: Brainstorming
EN: Collect ideas for and let participants comment on them. 
DE: Sammeln Sie Ideen und lassen Sie Teilnehmer*innen Ideen kommentieren.

EN: Phase 1: Create and comment on new ideas.
DE: Neue Ideen anlegen und kommentieren

2 
EN: Spatial Brainstorming
DE: Brainstorming mit Kartenfunktion
EN: Collect ideas and let participants locate them on a pre-defined area on a map
DE: Sammeln Sie Ideen, die von den Teilnehmer*innen auf einem vorher definierten Kartenausschnitt platziert werden können. 

EN: Phase 1: Create new ideas, locate them on a map and comment on them.
DE: Phase 1: Neue Ideen anlegen, auf der Karte platzieren und kommentieren.

3
EN: Spatial Idea Challenge
DE: Ideenwettbewerb mit Karte 
EN: Collect ideas on a pre-defined area on a map and let participants rate them in a second step. 
DE: Sammeln Sie Ideen, die von den Teilnehmer*innen auf einem vorher definierten Kartenausschnitt platziert werden können. Die Ideen können in einem zweiten Schritt bewertet werden.

EN: Phase 1: Create new ideas, locate them on a map and comment on them. 
EN: Phase 2: Rate the previously collected ideas to get quantitative feedback.

DE: Phase 1: Neue Ideen anlegen, auf der Karte platzieren und kommentieren.
DE: Phase 2: Die zuvor angelegten Ideen bewerten.

4
EN: Idea Challenge
DE: Ideenwettbewerb
EN: Collect ideas and let participants rate and comment on them in a second step. 
DE: Sammeln Sie Ideen und lassen sie sie durch die Teilnehmer*innen in einem zweiten Schritt bewerten.

EN: Phase 1: Create new ideas and comment on them.
EN: Phase 2: Rate the previously collected ideas.

DE: Phase 1: Neue Ideen anlegen und kommentieren.
DE: Phase 2: Die zuvor angelegten Ideen bewerten.

5
EN: Text Review
DE: Text kommentieren
EN: Let participants comment on paragraphs of a pre-defined text.
DE: Lassen Sie Teilnehmer*innen die Abschnitte/Absätze eines vorher eingestellten Textes kommentieren.

EN: Phase 1: Post comments on the paragraphs of the text
DE: Phase 1: Abschnitte/Absätze des Textes kommentieren. 

6 
EN: Poll
DE: Umfrage
EN: Let participants answer a poll with pre-defined questions and possible answers. 
DE: Lassen Sie Teilnehmer*innen auf eine oder mehrere Fragen mit vordefinierten Antwortmöglichkeiten antworten.  
EN: Phase 1: Answer the questions and discuss the poll.
DE: Phase 1: Auf Fragen antworten und Umfrage kommentieren.

7
EN: Participatory Budgeting
DE: Gemeinsame Budgetplanung

EN: Collect ideas with a budget proposal from participants. The ideas can be located on a pre-defined map.
DE: Sammeln Sie Ideen mit Budgetangabe von den Teilnehmer*innen. Die Ideen können auf einem vordefinierten Kartenausschnitt platziert werden. 

EN:  Phase 1: Post ideas with budget proposals, comment on them and rate them.
DE: Phase 1: Ideen mit Budgetangabe einreichen, kommentieren und bewerten.

8
EN: Face-to-Face Participation
DE: Vor-Ort-Beteiligung

EN: Inform your participants about events and phases of your participation process that take place offline. 
DE: Informieren Sie die Teilnehmer*innen über Veranstaltungen oder Phasen des Beteiligungsprozesses, die offline stattfinden.

EN: Phase 1: Show information about the face-to-face event/phase.
DE: Phase 1: Informationen über die Phase oder Veranstaltung werden angezeigt.

**Comment by rittermo** [comment]
The participatory budgeting text got lost. Will update

**Comment by rittermo** [comment]
The text is now complete!

**Comment by phillimorland** [comment]
@rittermo hi, i started updating the wording and some of it sounds a bit confusing in English the;
 
"Collect ideas and let participants locate them on a pre-defined area on a map"
the "locate them" bit sounds a bit off, here's some other suggestions;
"Collect ideas and let participants select a location on a pre-defined area on a map"
"Collect ideas with associated locations from a pre-defined area on a map"
"Collect ideas associated with a location within a pre-defined area on a map"

Also 
"Let participants answer a poll with pre-defined questions and possible answers."
alternative;
"Let participants answer a poll with pre-defined multiple choice questions."

**Comment by phillimorland** [comment]
also 
"Answer the questions and discuss the poll."
Do we discuss the poll?

**Comment by rittermo** [comment]
Hey @phillimorland ! Thank you so much for taking a look at this!

I like your suggestions 
For the first one, alternative 3 sounds great to my non-native ears.
Suggestions #2 also sound good. 
For #3 I agree with you, although the comment function is always active underneath the poll and it does allow responding to other comments. So “discuss” seems okay to me, but “comment on” might be more precise. So let’s go with that. 

Thank you again!
