### ISSUE TITLE
Follow function

### ISSUE THREAD

**Issue by phillimorland** [liqd/a4-product#738]
Auto following after participation does not show on the follow button if user has previously followed and un-followed that project

**Comment by MagdaN** [comment]
I think this is not a bug. The autofollow will only work once - so that I'll be a follower after I first added a comment or an idea to a project. If I then unfollow I  am not made follower again when I add another idea or comment. It would be annoying otherwise, right?

**Comment by phillimorland** [comment]
Good point! the behavior was a little different however; the first follow was not an auto follow, i clicked follow, I then clicked un-follow and I then participated. But still it's a total edge case so maybe it's not a problem?

**Comment by MagdaN** [comment]
There is a another issue that might cause the problem that you have? https://github.com/liqd/adhocracy4/issues/104

**Comment by MagdaN** [comment]
and here: https://github.com/liqd/a4-opin/issues/1086

**Comment by MagdaN** [comment]
maybe we should just fix it ;-)

**Comment by rittermo** [comment]
Thanks for identifying the issue, @phillimorland. I think it would be important to fix that, so I added it to a – brand new – milestone for this sprint.

**Comment by fuzzylogic2000** [comment]
@rittermo @phillimorland It shouldn't matter if the first follow was an autofollow or a voluntary follow. There should be no autofollowing after any unfollow!

**Comment by MagdaN** [comment]
Could we make a new userstory out of this and fix it for all projects, as this only came up when we were working on the newsletter. I already added a story to the technical backlog.

**Comment by rittermo** [comment]
Hmmm, I understand that you want to fix it for all platforms, but I would be a bit disappoingted that we have a user story that is only half-finished and feels broken. From a PO perspective investing 5 SP in that is a bit hard to swallow.

**Comment by MagdaN** [comment]
It has been broken for a very long time ...

**Comment by rittermo** [comment]
I understand, but I thought that fixing this particular issue here would be in the scope of this story.

**Comment by rittermo** [comment]
Okay, I tested this again and it works as expected for me. Once I clicked unfollow, I will not be automatically added as a follower again. I think we would need to explain this behavior better, but that is indeed for another user story. Thanks for the clarifications!
