### ISSUE TITLE
Newsletter: Accidentally sending multiple newsletters

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#751]
In the newsletter form in the dashboard, if I click multiple times on the send button before the confirmation page is loaded, in the newsletter form, I send multiple mails with the same newsletter to all recipients. I think this might not happen often, but it can happen accidentally (especially if load times are slow because of a bad connection) and be problematic if my project has a lot of followers.

**Comment by rittermo** [comment]
I think we need to block the send button after clicking it once. I would keep this in mind for another imoprovement story.

**Comment by fuzzylogic2000** [comment]
Alright, so this should be a US, not an issue!
