### ISSUE TITLE
#2060 use 1px dashed border for timeline line

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#802]
I think it would make more sense to use a 1px dashed line for the timeline line instead of the thicker 2px one (example below). I think it would make it easier to differentiate between the thick line of the tabs which switch the views and the timeline which is part of the participation tab. 

![Bildschirmfoto 2019-07-18 um 17 40 35](https://user-images.githubusercontent.com/15341015/61471767-9c52e900-a983-11e9-8ad5-f667bfe2fcf0.png)

**Comment by rittermo** [comment]
What do you think @szukowski ?

**Comment by szukowski** [comment]
@rittermo yes, it's better for a+, but m.b is the other way round. there the tabs have a thin line.
 @phillimorland can we then make a dotted line please
