### ISSUE TITLE
Registering: Terms of Use missing

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#82]
When registering link to Terms of Use are missing.

**Comment by xi** [comment]
To clarify: The link to the terms of use exists, but the page does not.

**Comment by MagdaN** [comment]
I added [wagtail site settings](http://docs.wagtail.io/en/v1.13.1/reference/contrib/settings.html) where the terms of use page can be set. I also added a PR (#156 ) which reads the right url from the settings.
