### ISSUE TITLE
#2151 change for form copy email

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#833]
In the email with the copy of the form content, for better readability there should be an empty line after each piece of data and the message text should start on a new line with an empty line afterwards.

<img width="593" alt="Bildschirmfoto 2019-07-29 um 15 29 16" src="https://user-images.githubusercontent.com/15341015/62052481-d343bd00-b215-11e9-8fa5-e9aa8d4dda1e.png">

**Comment by rittermo** [comment]
Oh, and could we use the name after „Guten Tag“ if it was given in the form? That would be quite nice

**Comment by MagdaN** [comment]
@rittermo its a bit tricky as the 'Guten Tag' cannot be changed so easily, so I will just add the blank lines
