### ISSUE TITLE
#2135 spacing and positioning

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-product#844]
in the layout the blocks filled the hole browser view or they have about 120 px padding top/ button. 
expample the first element: 
- please place the headline vertically in the middle
- the hole element is to narrow
- the space over the Image ist too smal

**Comment by phillimorland** [comment]
@szukowski the full height browser thing didn't work with positioning so we just have to do it with padding, you want 120px for desktop, how much for tablet and mobile? 
which element is too narrow?
