### ISSUE TITLE
#2135 font sizes and align

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-product#845]
the size are too smal. the distanz to the layout ist too high.

- titel is 36px should 50px
- all chapter(h2) is 24px should 40px
- headline (kostenlos, gemeinnützig ...) is 16px should 30px -> h3 headline medium
- headline (So einfach du ein Online-Beteiligungs- ...) is 16px should 30px -> h3 headline medium
- h4 headline smal for marginalien

- headline (lassen Sie uns sprechen) basic is serif, only the short highlight is bold
- links are serif text, not bold like headlines
- text lead ist 16px should 24px, any text associated with the chapter is a lead text and should have a larger font size
- standard font size is 16px should 18px (marginalien are )

**Comment by szukowski** [comment]
- headline (So einfach du ein Online-Beteiligungs- ...) align the color line also to the left

**Comment by phillimorland** [comment]
@szukowski I actually wanted to go through all this with you, i have made a kind of [style guide](https://product-dev.liqd.net/components/) in the comp lib which I wanted to go through with you and update all the sizes
