### ISSUE TITLE
#2135 mobile view on the tablet break

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-product#848]
the mobile view on the tablet break is not analogous to the design template

**Comment by szukowski** [comment]
![grafik](https://user-images.githubusercontent.com/36926290/62109322-544d9380-b2ac-11e9-9766-c82cb8fa7377.png)
![grafik](https://user-images.githubusercontent.com/36926290/62109351-63344600-b2ac-11e9-8c3a-2ef850368e29.png)
![grafik](https://user-images.githubusercontent.com/36926290/62109361-6b8c8100-b2ac-11e9-9cff-fdcb56945df9.png)

**Comment by phillimorland** [comment]
as discussed breakpoint it 768px same as testing hence appeared wrong
