### ISSUE TITLE
#2135 two-column element switches colors when adding additional columns

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#855]
I like that I can add more columns to the two-column element, but when I add two more columns to the two-column element, the colors change in a way that makes the CTA buttons illegible. Maybe the best would be if we could just repeat the order of the colors but in the reverse order per line. I think that might somehow be possible with n-th element pseudo selectors?

<img width="1349" alt="Bildschirmfoto 2019-07-30 um 17 14 25" src="https://user-images.githubusercontent.com/15341015/62141841-84695680-b2ed-11e9-9902-5e85676b9c35.png">

**Comment by phillimorland** [comment]
@rittermo that block has maximum of 2 cols, how did you add additional cols?

**Comment by phillimorland** [comment]
@rittermo i'm not sure why you can add second cols as it is set as maximum of 2 but if you want me to change styling to be able to add multiple cols to 1 block, what colours would you like them to be? just like they are but with visible btns?

**Comment by rittermo** [comment]
Yes, I think as they are but with visible buttons would be a nice option if we ever have the need for more columns in this block.

**Comment by phillimorland** [comment]
@rittermo this is actually becoming a bit of a time sink due to any fix involving nth or last child also requires there to be nested div which our tests and linter won't allow so i will put it aside for moment as we currently do not require more then 2 and revisit it

**Comment by rittermo** [comment]
Thanks for the update. Completely right to put it aside.

**Comment by fuzzylogic2000** [comment]
We have to deal with this if we want to change the landing page
