### ISSUE TITLE
Registration: Confirmation email text & language

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#89]
There are a couple of spelling and language mistakes in the confirmation email:

- parts of the texts are in German (registration happened in Safari (German) others are in english
- wrong support email address
- links to "contact" and "terms of use" working but no respective static pages ye
- space missing before Liquid Democracy e.V.

"Diese E-Mail wurde an r.brues+1@liqd.net gesendet. Wenn Sie sich nicht registriert haben können Sie diese E-Mail ignorieren. Wir werden Ihnen keine weiteren E-Mail senden. Falls Sie weitere Fragen haben, wenden Sie sich bitte an uns unter support-berlin@liqd.de_LIQD_PRODUCT_ is a participation platform operated byLiquid Democracy e.V., Am Sudhaus 2, D-12053 Berlin"

**Comment by kleingeist** [comment]
closed with #133
