### ISSUE TITLE
#2151 not possible to edit publication date of news

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#905]
It would be great to be able to edit the publication date of a news article (as we do it on liqd.net /blog)

**Comment by fuzzylogic2000** [comment]
It currently uses the first publication date. So you can write and save the draft before and then it gets that date when it's published, not when it was created. Is that enough or should we change it to a date you can set?

**Comment by rittermo** [comment]
I think that’s fine for now. Thank you!
