### ISSUE TITLE
#2151: underline for hover

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#907]
The underline for all of the text inside the teaser looks a bit strange as a hover effect. What was the original idea, for the mouse hover, @szukowski ?

![Bildschirmfoto 2019-08-13 um 15 34 41](https://user-images.githubusercontent.com/15341015/62945955-0ecab380-bde0-11e9-9b06-0a41ae163ece.png)

**Comment by fuzzylogic2000** [comment]
We added that to indicate that you can click. Would a background-color-change be better, @szukowski ?

**Comment by szukowski** [comment]
The whole element is clickable, but only the headline becomes underline. So it does not seem so massive.
