### ISSUE TITLE
Headline "Page Titel" too big on smartphone

### ISSUE THREAD

**Issue by szukowski** [liqd/a4-product#924]
on smartphones the "Page Titel" should 25% smaller then on Tablet or Desktop

Example:
Tablet, Desktop = 40px
Smartphone = 30px

or

Tablet, Desktop = 60px
Smartphone = 40px

**Comment by fuzzylogic2000** [comment]
Where is that? I tried it on the news list page and the title is 48 px on tablet and desktop and 36 px on mobile.
