### ISSUE TITLE
#2190 Share buttons don’t work

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#927]
There are some issues with the share buttons for use cases. 

For twitter, the URL is not added correctly. There is  an additional “https” added the URL

Facebook seems to work, but Facebook has a new share dialog which can be invoked via a different share URL pattern (see: https://developers.facebook.com/docs/sharing/reference/share-dialog)

The share button LinkedIn did not share anything in my testing but just made me visit LinkedIn.

**Comment by phillimorland** [comment]
@MagdaN can we have a look at the facebook thing together? I assume we want to use the url redirect to open a new page like we have with our other share btns but the unique app identifier requires additional javascript which i'm not sure about

**Comment by fuzzylogic2000** [comment]
@MagdaN Did you fix it? Can we close it?

**Comment by MagdaN** [comment]
@fuzzylogic2000 @phillimorland I fixed the url to the image so that all meta tags should work now. I did not implement the js facebbok dialog
