### ISSUE TITLE
Registration: re-direct not working

### ISSUE THREAD

**Issue by rukala** [liqd/a4-product#94]
When I start the registration process form one of the partner pages and then follow the confirmation link in the email I end up with a 404 after confirming it in my browser

**Comment by kleingeist** [comment]
the 404 is due to the missing front page.
the redirection target may be kept with a approach as in: 
https://github.com/liqd/a4-meinberlin/pull/1072

**Comment by xi** [comment]
Fixed in https://github.com/liqd/a4-product/pull/153
