### ISSUE TITLE
#2156 Header styling & positioning header elements

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#941]
logo and login links are not flush
    distances upwards and right / left should be uniform
    the menu icon has no colored background. turquoise is cta for the donation

Bildschirmfoto 2019-08-19 um 09 44 41

Bildschirmfoto 2019-08-19 um 09 50 41

Bildschirmfoto 2019-08-19 um 12 41 18

should
Bildschirmfoto 2019-08-19 um 12 45 15
Bildschirmfoto 2019-08-19 um 12 44 54
Bildschirmfoto 2019-08-19 um 12 44 33

https://github.com/liqd/adhocracy4/issues/386

**Comment by phillimorland** [comment]
@szukowski @rittermo if we remove background colour on cms header menu it will look very different to menu buttons on organisation and dashboard, colour can't be removed from them as they are attached to top ribbon, i'm not sure it might be confusing for buttons to look so different?

**Comment by fuzzylogic2000** [comment]
closed with #949
