### ISSUE TITLE
#2251: Notifications are sent for every new comment

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#988]
At the moment, when I follow a project, I get a notification for every new comment – not just every new idea, even if I am not the author of the idea.

Also, the notification says that a new idea (Beitrag) was posted to the project not a new comment.

Tested in: https://product-dev.liqd.net/teststadt/projects/innovationswettbewerb/
I posted comments as user m.ritter+2@liqd.net and received notifications as m.ritter@liqd.net

**Comment by fuzzylogic2000** [comment]
This should be fixed by now. Could you test again?

**Comment by fuzzylogic2000** [comment]
Switched off as part of story #2251
