### ISSUE TITLE
#2251: still receiving notifications about comments after unfollow

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-product#989]
I am still receiving a notification about a new comment on my idea even though I unfollowed the project. 

Tested in: https://product-dev.liqd.net/teststadt/projects/innovationswettbewerb/
Received notification as m.ritter+2@liqd.net

**Comment by fuzzylogic2000** [comment]
Yes, as should be stated in the reason (at the bottom of the email), you get these emails because you added a contribution [and the comments are answers to that contribution] and not because you follow the project. We cannot really change that.

**Comment by fuzzylogic2000** [comment]
ups, forgot to close yesterday!
