### ISSUE TITLE
do we also need the hourly_manage_task errored_task_notification?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#990]
It's in the taks of mB-dev, but not on prod-dev?!
@rmader

**Comment by rmader** [comment]
Sounds reasonable, see https://github.com/liqd/a4-product/pull/1021

Yesterday I looked into [django-cron](https://django-cron.readthedocs.io/en/latest/), which might be a more sensible solution in the long term, as we might want to increase the number of asynchronous jobs more and more. Maybe we can do a refactor sometime soon that moves most management commands to that, and then also move more stuff to A4.
